### ISSUE TITLE
TODO: fix root folder direct retrieval

### ISSUE THREAD

**Issue by itsWindows11** [itsWindows11/OwlCore.Storage.FluentFTP#1]
*From [UWP Community Discord discussion](https://discord.com/channels/372137812037730304/1253396992638455939/1253648379972423701):*
> Also we can't get an FtpFolder instance of the root folder currently, using the extension method on AsyncFtpClient I created for it just throws an exception because `GetObjectInfo` apparently doesn't work on the root folder (`/`)

Our `AsyncFtpClient.GetStorableFromPathAsync` method, which calls `GetObjectInfo`, errors when requesting the path `/`. Some FTP servers seem to support this feature (and thus will work normally as is), but we'd have to account for the servers that do not support it.

We could try to check if the path given is `/` then from there create our own `FtpListItem` with the info. Folder must be read only though as we can't move or copy or delete it (#2)

**Comment by Arlodotexe** [comment]
This is a curious quirk, does FluentFTP provide information on which FTP server implementations support this? 

- The complete list of server handlers can be found [here](https://github.com/robinrodricks/FluentFTP/tree/e673591c2683c443167e56347177a85340b62adb/FluentFTP/Servers/Handlers).
- The code where FluentFTP detects server capabilities with the FEAT command can be found [here](https://github.com/robinrodricks/FluentFTP/blob/e673591c2683c443167e56347177a85340b62adb/FluentFTP/Client/Modules/ServerFeatureModule.cs#L15).
- Drilling down further, the [`FtpCapability` enum](https://github.com/robinrodricks/FluentFTP/blob/e673591c2683c443167e56347177a85340b62adb/FluentFTP/Enums/FtpCapability.cs#L8) has a list of all capabilities supported by FluentFTP
- The complete list of supported commands for FTP in general can be found [here](https://ipfs.io/ipfs/bafybeiaysi4s6lnjev27ln5icwm6tueaw2vdykrtjkwiphwekaywqhcjze/wiki/List_of_FTP_commands).

I don't see anything related to getting the root directory, though there are dedicated commands for getting the parent. Where else would we look for this? 🤔

**Comment by itsWindows11** [comment]
I've read about it on a site that lists FTP server flags (`MLST` one to be exact), so it's not really related to FluentFTP. The workaround I noted here should work well enough, at least for enumerating items in it so it isn't entirely broken. You just can't get a machine listing (essentially what `AsyncFtpClient.GetObjectInfo` does) of `/` on some servers.

**Comment by itsWindows11** [comment]
Should be fixed with #4.
